#run the following command
# docker-compose up -d
version: '3.8'
services:
  ori-cspr:
    image: syntifi.com/ori-chains/ori-cspr
    environment:
      ORI_POSTGRES_HOST: ori-postgresql-prod
      ORI_POSTGRES_PORT: 5432
      ORI_POSTGRES_USER: quarkus_prod
      ORI_POSTGRES_PASSWORD: quarkus_prod
      ORI_POSTGRES_DB: quarkus_prod
      ORI_REST_API_SCHEME: http
      ORI_REST_API_ADDRESS: ori-api
      ORI_REST_API_PORT: 8080
      ORI_CHAIN_SCHEME: http
      ORI_CHAIN_ADDRESS: 74.208.245.69
      ORI_CHAIN_PORT: 7777
    networks:
      - ori

networks:
  ori:
    external: true