# make sure network ori exists.
# create running: `docker network create ori`
# then run the following command
# docker-compose up -d
version: '3.8'
services:
  ori-cspr:
    image: syntifi.com/ori/ori-chains/ori-cspr
    environment:
      ORI_BATCH_POSTGRES_HOST: ori-postgresql
      ORI_BATCH_POSTGRES_PORT: 5432
      ORI_BATCH_POSTGRES_USER: ori_db_user
      ORI_BATCH_POSTGRES_PASSWORD: ori_db_pwd
      ORI_BATCH_POSTGRES_DB: ori_db
      ORI_REST_API_SCHEME: http
      ORI_REST_API_ADDRESS: ori-api
      ORI_REST_API_PORT: 8080
      ORI_CHAIN_SCHEME: http
      ORI_CHAIN_ADDRESS: 45.76.251.225 # 'https://cspr.live/tools/peers' for fresh ones
      ORI_CHAIN_PORT: 7777
    networks:
      - ori

networks:
  ori:
    external: true