#run the following command
# docker-compose up -d
version: '2.1'
services:
  ori_postgresql_prod:
    image: postgres:13.1
    environment:
      POSTGRES_USER: quarkus_prod
      POSTGRES_PASSWORD: quarkus_prod
      POSTGRES_DB: quarkus_prod
    ports:
      - 5432:5432
    networks:
      - ori 

  ori:
    image: ori-native
    depends_on:
      - ori_postgresql_prod
    environment:
      ORI_POSTGRES_HOST: ori_postgresql_prod
      ORI_POSTGRES_PORT: 5432
      ORI_POSTGRES_USER: quarkus_prod
      ORI_POSTGRES_PASSWORD: quarkus_prod
      ORI_POSTGRES_DB: quarkus_prod
      ORI_AML_REPORTING_THRESHOLD: 10000 
      ORI_AML_LONG_WINDOW_DAYS: 30 
      ORI_AML_MID_WINDOW_DAYS: 14
      ORI_AML_SHORT_WINDOW_DAYS: 7
      ORI_AML_MAX_TRACE_LENGTH: 200
    ports:
      - 8080:8080
    networks:
      - ori 

networks:
  ori:
    driver: bridge 