#run the following command
# docker-compose up -d
version: '3.8'
services:
  geth-node:
    image: ethereum/client-go:latest
    hostname: geth-node
    command: --syncmode "full" --cache=512 --http --http.addr "0.0.0.0" --http.vhosts=*
    volumes:
      - e:/tmp/eth:/root/:ethereum
    networks:
      - ori

  ori-eth:
    image: syntifi.com/ori-chains/ori-eth
    depends_on:
      - geth-node
    environment:
      ORI_POSTGRES_HOST: ori-postgresql-prod
      ORI_POSTGRES_PORT: 5432
      ORI_POSTGRES_USER: quarkus_prod
      ORI_POSTGRES_PASSWORD: quarkus_prod
      ORI_POSTGRES_DB: quarkus_prod
      ORI_REST_API_SCHEME: http
      ORI_REST_API_ADDRESS: ori-api
      ORI_REST_API_PORT: 8080
      ORI_CHAIN_SCHEME: http
      ORI_CHAIN_ADDRESS: geth-node
      ORI_CHAIN_PORT: 8545
    networks:
      - ori

networks:
  ori:
    external: true